path=("$HOME/.local/bin" $path)

# Homebrew
export HOMEBREW_BUNDLE_FILE="$HOME/.config/Brewfile"
export HOMEBREW_NO_ENV_HINTS=1
eval "$(/opt/homebrew/bin/brew shellenv)"

export EDITOR='vim'

# zsh
eval "$(sheldon source)"

# Aliases
alias reload='source ~/.zshrc'
alias rm='trash'
alias vim='nvim'
alias e='eza -l -h --no-permissions --no-user --icons --group-directories-first'


# Git
alias gap='git add -p'
alias gb='git branch -v'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias glg='git log --graph --decorate --oneline --abbrev-commit'
alias gll='git log --oneline'
alias gp='git push origin HEAD'
alias gpp='git push -u origin HEAD'
alias gs='git status -sb'

# SDKMAN
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

# node
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"

# per-machine specific configuration
[[ -f "$HOME/.custom.zsh" ]] && source "$HOME/.custom.zsh"
